const ROLE = Object.freeze({
  ADMIN: 'Admin',
  CLIENT_ADVISOR: 'Client Advisor',
  JOC: 'JOC',
  DIAMOND_ORDER_ADMIN: 'Diamond Order Admin',
  DIAMOND_ORDER_ASSISTANT: 'Diamond Order Assistant',
  READ_ONLY_VIEWER: 'Read-Only Viewer',
});

const BOOKING_SOURCE = Object.freeze({
  ACUITY: 'acuity',
  CALENDLY: 'calendly',
  MANUAL: 'manual',
  TEST: 'test',
});

const APPOINTMENT_STATUS = Object.freeze({
  ACTIVE: 'active',
  CANCELED: 'canceled',
  RESCHEDULED: 'rescheduled',
  COMPLETED: 'completed',
  NO_SHOW: 'no_show',
});

const ROOT_LIFECYCLE_STATE = Object.freeze({
  ACTIVE: 'Active',
  CLOSED_WON: 'Closed Won',
  CLOSED_LOST: 'Closed Lost',
  ARCHIVED: 'Archived',
});

const SALES_STAGE = Object.freeze({
  NEW_LEAD: 'New Lead',
  APPOINTMENT_BOOKED: 'Appointment Booked',
  CONSULT_COMPLETE: 'Consult Complete',
  QUOTE_SENT: 'Quote Sent',
  DEPOSIT_RECEIVED: 'Deposit Received',
  IN_PRODUCTION: 'In Production',
  COMPLETE: 'Complete',
  LOST: 'Lost',
});

const TASK_STATE = Object.freeze({
  OPEN: 'Open',
  CLAIMED: 'Claimed',
  SNOOZED: 'Snoozed',
  BLOCKED: 'Blocked',
  COMPLETED: 'Completed',
  CANCELED: 'Canceled',
});

const TASK_TYPE = Object.freeze({
  ASSIGN_APPOINTMENT: 'ASSIGN_APPOINTMENT',
  SEND_HYBRID_WELCOME: 'SEND_HYBRID_WELCOME',
  SEND_WELCOME: 'SEND_WELCOME',
  SEND_MAP_INSTRUCTIONS: 'SEND_MAP_INSTRUCTIONS',
  REVIEW_APPOINTMENT: 'REVIEW_APPOINTMENT',
  APPOINTMENT_DAY_CHECKLIST: 'APPOINTMENT_DAY_CHECKLIST',
  APPROVE_RECAP_MESSAGE: 'APPROVE_RECAP_MESSAGE',
  SEND_FINAL_RECAP: 'SEND_FINAL_RECAP',
  POST_CONSULT_CLIENT_STATUS: 'POST_CONSULT_CLIENT_STATUS',
  START_3D_DESIGN: 'START_3D_DESIGN',
  RECORD_3D_DEADLINE: 'RECORD_3D_DEADLINE',
  REQUEST_WAX_PRINT: 'REQUEST_WAX_PRINT',
  UPDATE_WAX_REQUEST: 'UPDATE_WAX_REQUEST',
  PROPOSE_DIAMONDS: 'PROPOSE_DIAMONDS',
  PREPARE_DV_QUOTATION: 'PREPARE_DV_QUOTATION',
  ORDER_DIAMONDS: 'ORDER_DIAMONDS',
  TRACK_DIAMONDS: 'TRACK_DIAMONDS',
  CONFIRM_DIAMOND_DELIVERY: 'CONFIRM_DIAMOND_DELIVERY',
  ACK_DIAMONDS_ORDERED_ASSIGNED_REP: 'ACK_DIAMONDS_ORDERED_ASSIGNED_REP',
  ACK_DIAMONDS_ORDERED_JOC: 'ACK_DIAMONDS_ORDERED_JOC',
  RECORD_DIAMOND_DECISIONS: 'RECORD_DIAMOND_DECISIONS',
  RETURN_DIAMONDS: 'RETURN_DIAMONDS',
  REVIEW_DIAMOND_ETA_ASSIGNED_REP: 'REVIEW_DIAMOND_ETA_ASSIGNED_REP',
  REVIEW_DIAMOND_ETA_JOC: 'REVIEW_DIAMOND_ETA_JOC',
  CUSTOMER_DATA_CLEANUP_REVIEW: 'CUSTOMER_DATA_CLEANUP_REVIEW',
  CUSTOMER_DATA_CLEANUP_CONFIRM: 'CUSTOMER_DATA_CLEANUP_CONFIRM',
  CUSTOMER_DATA_CLEANUP_REVISE: 'CUSTOMER_DATA_CLEANUP_REVISE',
});

const ARTIFACT_STAGE = Object.freeze({
  UPLOADED: 'UPLOADED',
  TRANSCRIPTION_QUEUED: 'TRANSCRIPTION_QUEUED',
  TRANSCRIBING: 'TRANSCRIBING',
  TRANSCRIPT_READY: 'TRANSCRIPT_READY',
  SUMMARY_READY: 'SUMMARY_READY',
  APPROVED: 'APPROVED',
  JOC_HANDOFF: 'JOC_HANDOFF',
  MANUAL_REVIEW: 'MANUAL_REVIEW',
});

const CACHE_SLICE = Object.freeze({
  TASK_LIST: 'TaskListSlice',
  TASK_DETAIL: 'TaskDetailSlice',
  CUSTOMER_CARD: 'CustomerCardSlice',
  CUSTOMER_ROOT_DETAIL: 'CustomerRootDetailSlice',
  CALENDAR_MONTH: 'CalendarMonthSlice',
  APPOINTMENT_BRIEF: 'AppointmentBriefSlice',
  ADMIN_HEALTH: 'AdminHealthSlice',
  DIAMOND_INVENTORY: 'DiamondInventorySlice',
  DIAMOND_TRACKING: 'DiamondTrackingSlice',
  DIAMOND_ROOT: 'DiamondRootSlice',
  PAYMENT_SUMMARY: 'PaymentSummarySlice',
  FORM_OPTIONS: 'FormOptionsSlice',
});
