const TAB_NAMES = Object.freeze({
  AppointmentEvents: '01_AppointmentEvents',
  RootAppointments: '02_RootAppointments',
  CustomerInfo: '03_CustomerInfo',
  ClientStatus: '04_ClientStatus',
  ClientStatusHistory: '04_ClientStatusHistory',
  Order3D: '05_Order3D',
  Order3DHistory: '05_Order3DHistory',
  WaxRequests: '05_WaxRequests',
  DiamondViewing: '06_DiamondViewing',
  Stones: '_Stones',
  StonesSync: '_StonesSync',
  TaskQueue: '_TaskQueue',
  TaskLog: '_TaskLog',
  AppointmentArtifacts: '_AppointmentArtifacts',
  Users: '_Users',
  RosterSchedule: '_RosterSchedule',
  ScheduleChanges: '_ScheduleChanges',
  Config: '_Config',
  Templates: '_Templates',
  DataCleanup: '_DataCleanup',
  IntakeQueue: '_IntakeQueue',
  DataFlowRef: '_DataFlowRef',
  SchemaVersion: '_SchemaVersion',
  OpsLog: '_OpsLog',
});

const TAB_OWNER_REPOS = Object.freeze({
  AppointmentEvents: '04_Repo_Appointments.gs',
  RootAppointments: '04_Repo_RootAppointments.gs',
  CustomerInfo: '04_Repo_CustomerInfo.gs',
  ClientStatus: '04_Repo_ClientStatus.gs',
  ClientStatusHistory: '04_Repo_ClientStatus.gs',
  Order3D: '04_Repo_Order3D.gs',
  Order3DHistory: '04_Repo_Order3D.gs',
  WaxRequests: '04_Repo_Wax.gs',
  DiamondViewing: '04_Repo_DiamondViewing.gs',
  Stones: '04_Repo_Stones.gs',
  StonesSync: '04_Repo_Stones.gs',
  TaskQueue: '04_Repo_Tasks.gs',
  TaskLog: '04_Repo_Tasks.gs',
  AppointmentArtifacts: '04_Repo_Artifacts.gs',
  Users: '04_Repo_Users.gs',
  RosterSchedule: '04_Repo_Schedules.gs',
  ScheduleChanges: '04_Repo_Schedules.gs',
  Config: '04_Repo_Config.gs',
  Templates: '04_Repo_Templates.gs',
  DataCleanup: '04_Repo_DataCleanup.gs',
  IntakeQueue: '04_Repo_IntakeQueue.gs',
  DataFlowRef: '00_Setup_Schema.gs',
  SchemaVersion: '00_Setup_Schema.gs',
  OpsLog: '04_Repo_OpsLog.gs',
});

const TAB_ORDER = Object.freeze([
  'AppointmentEvents',
  'RootAppointments',
  'CustomerInfo',
  'ClientStatus',
  'ClientStatusHistory',
  'Order3D',
  'Order3DHistory',
  'WaxRequests',
  'DiamondViewing',
  'Stones',
  'StonesSync',
  'TaskQueue',
  'TaskLog',
  'AppointmentArtifacts',
  'Users',
  'RosterSchedule',
  'ScheduleChanges',
  'Config',
  'Templates',
  'DataCleanup',
  'IntakeQueue',
  'DataFlowRef',
  'SchemaVersion',
  'OpsLog',
]);
