const SCHEMA_VERSION_TARGET = '0.3.0';

function col_(col, type, required, width, notes) {
  return Object.freeze({
    col: col,
    type: type,
    required: required,
    width: width,
    notes: notes || '',
  });
}

const SCHEMA_COLUMNS_BY_TAB_KEY = Object.freeze({
  AppointmentEvents: Object.freeze({
    APPT_ID: col_(1, 'string', true, 150, 'Primary event key.'),
    RootApptID: col_(2, 'string', true, 150, 'Groups events into one customer journey.'),
    Version: col_(3, 'integer', true, 70, 'Optimistic concurrency version.'),
    UpdatedAt: col_(4, 'datetime', true, 150),
    UpdatedBy: col_(5, 'string', false, 140),
    UpdatedByEmail: col_(6, 'string', false, 210),
    BookingSource: col_(7, 'enum', true, 120, 'acuity or manual.'),
    ExternalBookingId: col_(8, 'string', false, 170, 'Native source appointment id.'),
    ExternalBookingUrl: col_(9, 'url', false, 220),
    SourcePayloadHash: col_(10, 'string', false, 160),
    SourceMetadataJson: col_(11, 'json', false, 240),
    VisitType: col_(12, 'string', false, 160),
    Brand: col_(13, 'string', false, 120),
    AppointmentStatus: col_(14, 'enum', true, 140),
    AppointmentStart: col_(15, 'datetime', false, 160),
    AppointmentEnd: col_(16, 'datetime', false, 160),
    AppointmentDate: col_(17, 'date', false, 130),
    AppointmentTime: col_(18, 'time', false, 120),
    TimeZone: col_(19, 'string', false, 130),
    BookedAt: col_(20, 'datetime', false, 150),
    CanceledAt: col_(21, 'datetime', false, 150),
    RescheduledAt: col_(22, 'datetime', false, 150),
    RescheduledFrom: col_(23, 'string', false, 150),
    RescheduledTo: col_(24, 'string', false, 150),
    Outcome: col_(25, 'enum', false, 140),
    NoShowReason: col_(26, 'string', false, 180),
    CustomerNameRaw: col_(27, 'string', false, 210),
    CustomerEmailRaw: col_(28, 'string', false, 220),
    CustomerPhoneRaw: col_(29, 'string', false, 160),
    EmailLower: col_(30, 'string', false, 220),
    PhoneNorm: col_(31, 'string', false, 160),
    AppointmentFolderId: col_(32, 'string', false, 180),
    AppointmentFolderUrl: col_(33, 'url', false, 240),
    Notes: col_(34, 'string', false, 260),
  }),

  RootAppointments: Object.freeze({
    RootApptID: col_(1, 'string', true, 150),
    Version: col_(2, 'integer', true, 70),
    UpdatedAt: col_(3, 'datetime', true, 150),
    UpdatedBy: col_(4, 'string', false, 140),
    UpdatedByEmail: col_(5, 'string', false, 210),
    CurrentAPPT_ID: col_(6, 'string', false, 150),
    LatestAPPT_ID: col_(7, 'string', false, 150),
    RootLifecycleState: col_(8, 'enum', true, 150),
    RootVersion: col_(9, 'integer', true, 90),
    FirstBookedAt: col_(10, 'datetime', false, 150),
    LastActivityAt: col_(11, 'datetime', false, 150),
    IsActive: col_(12, 'boolean', true, 90),
    ClosedAt: col_(13, 'datetime', false, 150),
    CloseReason: col_(14, 'string', false, 180),
    Notes: col_(15, 'string', false, 260),
  }),

  CustomerInfo: Object.freeze({
    RootApptID: col_(1, 'string', true, 150),
    Version: col_(2, 'integer', true, 70),
    UpdatedAt: col_(3, 'datetime', true, 150),
    UpdatedBy: col_(4, 'string', false, 140),
    UpdatedByEmail: col_(5, 'string', false, 210),
    CustomerName: col_(6, 'string', true, 220),
    FirstName: col_(7, 'string', false, 140),
    LastName: col_(8, 'string', false, 140),
    Phone: col_(9, 'string', false, 160),
    PhoneNorm: col_(10, 'string', false, 160),
    Email: col_(11, 'string', false, 220),
    EmailLower: col_(12, 'string', false, 220),
    Brand: col_(13, 'string', false, 120),
    ClientAdvisorName: col_(14, 'string', false, 180),
    ClientAdvisorEmail: col_(15, 'string', false, 220),
    JOCOwnerName: col_(16, 'string', false, 180),
    JOCOwnerEmail: col_(17, 'string', false, 220),
    CustomerFolderId: col_(18, 'string', false, 180),
    CustomerFolderUrl: col_(19, 'url', false, 240),
    LeadSource: col_(20, 'string', false, 160),
    LeadIdentity: col_(21, 'string', false, 180),
    PreferredContactMethod: col_(22, 'enum', false, 160),
    Notes: col_(23, 'string', false, 260),
  }),

  ClientStatus: Object.freeze({
    RootApptID: col_(1, 'string', true, 150),
    Version: col_(2, 'integer', true, 70),
    UpdatedAt: col_(3, 'datetime', true, 150),
    UpdatedBy: col_(4, 'string', false, 140),
    UpdatedByEmail: col_(5, 'string', false, 210),
    SalesStage: col_(6, 'enum', true, 150),
    ConversionStatus: col_(7, 'enum', false, 160),
    CustomOrderStatus: col_(8, 'enum', false, 170),
    InProductionStatus: col_(9, 'enum', false, 170),
    CenterStoneStatus: col_(10, 'enum', false, 170),
    NextSteps: col_(11, 'string', false, 280),
    NextStepsUpdatedAt: col_(12, 'datetime', false, 160),
    OrderDate: col_(13, 'date', false, 130),
    Deadline3D: col_(14, 'date', false, 130),
    Deadline3DOriginal: col_(15, 'date', false, 150),
    Deadline3DMoveCount: col_(16, 'integer', true, 120),
    Deadline3DMoveReason: col_(17, 'string', false, 220),
    Deadline3DUpdatedAt: col_(18, 'datetime', false, 160),
    Is3DNeeded: col_(19, 'boolean', false, 110),
    IsWaxNeeded: col_(20, 'boolean', false, 110),
    LastPaymentStageChangeAt: col_(21, 'datetime', false, 190),
    Notes: col_(22, 'string', false, 260),
  }),

  ClientStatusHistory: Object.freeze({
    HistoryID: col_(1, 'string', true, 160),
    RootApptID: col_(2, 'string', true, 150),
    Version: col_(3, 'integer', true, 70),
    ChangedAt: col_(4, 'datetime', true, 150),
    ActorName: col_(5, 'string', false, 160),
    ActorEmail: col_(6, 'string', false, 220),
    Source: col_(7, 'string', true, 140),
    FieldName: col_(8, 'string', true, 180),
    OldValue: col_(9, 'string', false, 220),
    NewValue: col_(10, 'string', false, 220),
    ChangeReason: col_(11, 'string', false, 240),
    MetadataJson: col_(12, 'json', false, 240),
  }),

  Order3D: Object.freeze({
    RootApptID: col_(1, 'string', true, 150),
    Version: col_(2, 'integer', true, 70),
    UpdatedAt: col_(3, 'datetime', true, 150),
    UpdatedBy: col_(4, 'string', false, 140),
    UpdatedByEmail: col_(5, 'string', false, 210),
    SONumber: col_(6, 'string', false, 130),
    OdooUrl: col_(7, 'url', false, 240),
    DesignRequest: col_(8, 'string', false, 280),
    TrackerUrl: col_(9, 'url', false, 240),
    OrderFolderId: col_(10, 'string', false, 180),
    OrderFolderUrl: col_(11, 'url', false, 240),
    Current3DState: col_(12, 'enum', false, 160),
    LastRevisionAt: col_(13, 'datetime', false, 150),
    RevisionCount: col_(14, 'integer', true, 110),
    ManufacturingNotes: col_(15, 'string', false, 260),
    Notes: col_(16, 'string', false, 260),
  }),

  Order3DHistory: Object.freeze({
    HistoryID: col_(1, 'string', true, 160),
    RootApptID: col_(2, 'string', true, 150),
    Version: col_(3, 'integer', true, 70),
    ChangedAt: col_(4, 'datetime', true, 150),
    ActorName: col_(5, 'string', false, 160),
    ActorEmail: col_(6, 'string', false, 220),
    Source: col_(7, 'string', true, 140),
    EventType: col_(8, 'enum', true, 150),
    SONumber: col_(9, 'string', false, 130),
    OldValue: col_(10, 'string', false, 220),
    NewValue: col_(11, 'string', false, 220),
    RevisionRequest: col_(12, 'string', false, 260),
    TrackerUrl: col_(13, 'url', false, 240),
    MetadataJson: col_(14, 'json', false, 240),
  }),

  WaxRequests: Object.freeze({
    WaxRequestID: col_(1, 'string', true, 160),
    RootApptID: col_(2, 'string', true, 150),
    Version: col_(3, 'integer', true, 70),
    UpdatedAt: col_(4, 'datetime', true, 150),
    UpdatedBy: col_(5, 'string', false, 140),
    UpdatedByEmail: col_(6, 'string', false, 210),
    RequestStatus: col_(7, 'enum', true, 150),
    AdminDeadline: col_(8, 'date', false, 140),
    RequestUrl: col_(9, 'url', false, 240),
    WaxFolderId: col_(10, 'string', false, 180),
    WaxFolderUrl: col_(11, 'url', false, 240),
    RequestedAt: col_(12, 'datetime', false, 150),
    CompletedAt: col_(13, 'datetime', false, 150),
    Notes: col_(14, 'string', false, 260),
  }),

  DiamondViewing: Object.freeze({
    RootApptID: col_(1, 'string', true, 150),
    Version: col_(2, 'integer', true, 70),
    UpdatedAt: col_(3, 'datetime', true, 150),
    UpdatedBy: col_(4, 'string', false, 140),
    UpdatedByEmail: col_(5, 'string', false, 210),
    WorkflowState: col_(6, 'enum', true, 150),
    StoneType: col_(7, 'string', false, 140),
    ShapePreference: col_(8, 'string', false, 160),
    CaratMin: col_(9, 'number', false, 100),
    CaratMax: col_(10, 'number', false, 100),
    ColorRange: col_(11, 'string', false, 140),
    ClarityRange: col_(12, 'string', false, 140),
    BudgetNote: col_(13, 'string', false, 200),
    PrimaryDecidingFactor: col_(14, 'string', false, 200),
    RatioPreference: col_(15, 'string', false, 160),
    VarietyStrategy: col_(16, 'string', false, 220),
    LookingForSummary: col_(17, 'string', false, 260),
    InternalNotes: col_(18, 'string', false, 260),
    LastProposalAt: col_(19, 'datetime', false, 150),
    DecisionsRecordedAt: col_(20, 'datetime', false, 170),
  }),

  Stones: Object.freeze({
    CertNo: col_(1, 'string', true, 170, 'Canonical stone key.'),
    Version: col_(2, 'integer', true, 70),
    UpdatedAt: col_(3, 'datetime', true, 150),
    UpdatedByEmail: col_(4, 'string', false, 220),
    Vendor: col_(5, 'string', false, 160),
    Lab: col_(6, 'string', false, 100),
    Shape: col_(7, 'string', false, 130),
    Carat: col_(8, 'number', false, 100),
    Color: col_(9, 'string', false, 100),
    Clarity: col_(10, 'string', false, 110),
    Cut: col_(11, 'string', false, 110),
    Polish: col_(12, 'string', false, 110),
    Symmetry: col_(13, 'string', false, 110),
    Fluorescence: col_(14, 'string', false, 130),
    Measurements: col_(15, 'string', false, 170),
    Ratio: col_(16, 'number', false, 90),
    StoneStatus: col_(17, 'enum', true, 140, 'In Stock, Out, Returned, Sold.'),
    OrderStatus: col_(18, 'enum', false, 150, 'Proposing, On the Way, Delivered, Not Approved, Returned, Sold.'),
    Decision: col_(19, 'string', false, 140),
    ReturnStatus: col_(20, 'string', false, 150),
    ReturnDueDate: col_(21, 'date', false, 140),
    TrackingETA: col_(22, 'datetime', false, 150),
    TrackingStatus: col_(23, 'string', false, 160),
    Carrier: col_(24, 'string', false, 130),
    TrackingNumber: col_(25, 'string', false, 170),
    TrackingUrl: col_(26, 'url', false, 240),
    MemoDate: col_(27, 'date', false, 130),
    InvoiceDate: col_(28, 'date', false, 130),
    OrderedByEmail: col_(29, 'string', false, 220),
    OrderedDate: col_(30, 'datetime', false, 150),
    PurchasedDate: col_(31, 'date', false, 130),
    LastTrackingCheckAt: col_(32, 'datetime', false, 170),
    JOCHandoffAt: col_(33, 'datetime', false, 150),
    AssignedRootApptID: col_(34, 'string', false, 160),
    Holder: col_(35, 'string', false, 180),
    CustomerName: col_(36, 'string', false, 220),
    ClientAdvisorEmail: col_(37, 'string', false, 220),
    JOCOwnerEmail: col_(38, 'string', false, 220),
    ReturnNotes: col_(39, 'string', false, 260),
    SourceMetadataJson: col_(40, 'json', false, 260),
    Notes: col_(41, 'string', false, 260),
  }),

  StonesSync: Object.freeze({
    SyncID: col_(1, 'string', true, 170),
    Version: col_(2, 'integer', true, 70),
    AppliedAt: col_(3, 'datetime', true, 150),
    AppliedByEmail: col_(4, 'string', false, 220),
    FileID: col_(5, 'string', false, 180),
    SourceRows: col_(6, 'integer', true, 110),
    Matched: col_(7, 'integer', true, 100),
    Updated: col_(8, 'integer', true, 100),
    Appended: col_(9, 'integer', true, 100),
    Skipped: col_(10, 'integer', true, 100),
    ConflictsJson: col_(11, 'json', false, 260),
    SyncNotes: col_(12, 'string', false, 300),
  }),

  TaskQueue: Object.freeze({
    TaskID: col_(1, 'string', true, 160),
    RootApptID: col_(2, 'string', false, 150),
    APPT_ID: col_(3, 'string', false, 150),
    Version: col_(4, 'integer', true, 70),
    UpdatedAt: col_(5, 'datetime', true, 150),
    CreatedAt: col_(6, 'datetime', true, 150),
    CreatedBy: col_(7, 'string', false, 160),
    TaskType: col_(8, 'enum', true, 220),
    TaskState: col_(9, 'enum', true, 140),
    OwnerRole: col_(10, 'enum', false, 180),
    OwnerEmail: col_(11, 'string', false, 220),
    OwnerName: col_(12, 'string', false, 180),
    DueAt: col_(13, 'datetime', false, 150),
    SnoozedUntil: col_(14, 'datetime', false, 150),
    SnoozeReason: col_(15, 'string', false, 220),
    ClaimedByEmail: col_(16, 'string', false, 220),
    ClaimedAt: col_(17, 'datetime', false, 150),
    BlockReason: col_(18, 'string', false, 220),
    CompletedAt: col_(19, 'datetime', false, 150),
    CompletedByEmail: col_(20, 'string', false, 220),
    TemplateKey: col_(21, 'string', false, 170),
    PayloadJson: col_(22, 'json', false, 260),
    InvalidatesJson: col_(23, 'json', false, 220),
  }),

  TaskLog: Object.freeze({
    TaskLogID: col_(1, 'string', true, 160),
    TaskID: col_(2, 'string', true, 160),
    RootApptID: col_(3, 'string', false, 150),
    Version: col_(4, 'integer', true, 70),
    EventAt: col_(5, 'datetime', true, 150),
    ActorEmail: col_(6, 'string', false, 220),
    EventType: col_(7, 'enum', true, 150),
    OldState: col_(8, 'enum', false, 140),
    NewState: col_(9, 'enum', false, 140),
    Notes: col_(10, 'string', false, 260),
    MetadataJson: col_(11, 'json', false, 240),
  }),

  AppointmentArtifacts: Object.freeze({
    ArtifactID: col_(1, 'string', true, 160),
    RootApptID: col_(2, 'string', true, 150),
    APPT_ID: col_(3, 'string', false, 150),
    TaskID: col_(4, 'string', false, 160),
    Version: col_(5, 'integer', true, 70),
    UpdatedAt: col_(6, 'datetime', true, 150),
    CreatedAt: col_(7, 'datetime', true, 150),
    ArtifactType: col_(8, 'enum', true, 150),
    WorkflowStage: col_(9, 'enum', true, 180),
    DriveFileId: col_(10, 'string', false, 180),
    DriveFileUrl: col_(11, 'url', false, 240),
    DriveFolderId: col_(12, 'string', false, 180),
    TranscriptId: col_(13, 'string', false, 180),
    TranscriptDocUrl: col_(14, 'url', false, 240),
    SummaryDocUrl: col_(15, 'url', false, 240),
    SummaryJsonFileId: col_(16, 'string', false, 180),
    ApprovedAt: col_(17, 'datetime', false, 150),
    ApprovedByEmail: col_(18, 'string', false, 220),
    JOCHandoffAt: col_(19, 'datetime', false, 150),
    Attempts: col_(20, 'integer', true, 90),
    LastError: col_(21, 'string', false, 260),
    MetadataJson: col_(22, 'json', false, 240),
  }),

  Users: Object.freeze({
    Email: col_(1, 'string', true, 220),
    Version: col_(2, 'integer', true, 70),
    UpdatedAt: col_(3, 'datetime', true, 150),
    UpdatedByEmail: col_(4, 'string', false, 220),
    Name: col_(5, 'string', true, 180),
    RolesCsv: col_(6, 'string', true, 260),
    Active: col_(7, 'boolean', true, 90),
    PasswordSalt: col_(8, 'string', false, 180),
    PasswordHash: col_(9, 'string', false, 220),
    LastLoginAt: col_(10, 'datetime', false, 150),
    Notes: col_(11, 'string', false, 260),
  }),

  RosterSchedule: Object.freeze({
    ScheduleID: col_(1, 'string', true, 160),
    Email: col_(2, 'string', true, 220),
    Version: col_(3, 'integer', true, 70),
    UpdatedAt: col_(4, 'datetime', true, 150),
    UpdatedByEmail: col_(5, 'string', false, 220),
    WeekStart: col_(6, 'date', true, 130),
    Role: col_(7, 'enum', true, 180),
    Monday: col_(8, 'string', false, 140),
    Tuesday: col_(9, 'string', false, 140),
    Wednesday: col_(10, 'string', false, 140),
    Thursday: col_(11, 'string', false, 140),
    Friday: col_(12, 'string', false, 140),
    Saturday: col_(13, 'string', false, 140),
    Sunday: col_(14, 'string', false, 140),
    JOCRoutingEmail: col_(15, 'string', false, 220),
    SkillTagsCsv: col_(16, 'string', false, 220),
    Active: col_(17, 'boolean', true, 90),
    Notes: col_(18, 'string', false, 260),
  }),

  ScheduleChanges: Object.freeze({
    ScheduleChangeID: col_(1, 'string', true, 180),
    Email: col_(2, 'string', true, 220),
    Version: col_(3, 'integer', true, 70),
    ChangedAt: col_(4, 'datetime', true, 150),
    ChangedByEmail: col_(5, 'string', false, 220),
    ChangeDate: col_(6, 'date', true, 130),
    AvailabilityState: col_(7, 'enum', true, 170),
    StartTime: col_(8, 'time', false, 120),
    EndTime: col_(9, 'time', false, 120),
    Reason: col_(10, 'string', false, 220),
    Notes: col_(11, 'string', false, 260),
  }),

  Config: Object.freeze({
    Section: col_(1, 'string', true, 160),
    Key: col_(2, 'string', true, 180),
    Version: col_(3, 'integer', true, 70),
    UpdatedAt: col_(4, 'datetime', true, 150),
    UpdatedByEmail: col_(5, 'string', false, 220),
    Value: col_(6, 'string', false, 260),
    ValueType: col_(7, 'enum', true, 120),
    EditableByAdmin: col_(8, 'boolean', true, 130),
    Description: col_(9, 'string', false, 300),
  }),

  Templates: Object.freeze({
    TemplateKey: col_(1, 'string', true, 180),
    Version: col_(2, 'integer', true, 70),
    UpdatedAt: col_(3, 'datetime', true, 150),
    UpdatedByEmail: col_(4, 'string', false, 220),
    TaskType: col_(5, 'enum', true, 220),
    Channel: col_(6, 'enum', false, 120),
    Subject: col_(7, 'string', false, 220),
    Body: col_(8, 'string', false, 360),
    Active: col_(9, 'boolean', true, 90),
    Notes: col_(10, 'string', false, 260),
  }),

  DataCleanup: Object.freeze({
    CaseID: col_(1, 'string', true, 160),
    RootApptID: col_(2, 'string', true, 150),
    Version: col_(3, 'integer', true, 70),
    UpdatedAt: col_(4, 'datetime', true, 150),
    CreatedAt: col_(5, 'datetime', true, 150),
    AssignedToEmail: col_(6, 'string', false, 220),
    CaseState: col_(7, 'enum', true, 150),
    IssueType: col_(8, 'enum', true, 180),
    ProposedChangesJson: col_(9, 'json', false, 260),
    AdminDecision: col_(10, 'enum', false, 160),
    AdminNotes: col_(11, 'string', false, 260),
    CompletedAt: col_(12, 'datetime', false, 150),
  }),

  IntakeQueue: Object.freeze({
    IntakeID: col_(1, 'string', true, 170),
    Version: col_(2, 'integer', true, 70),
    CreatedAt: col_(3, 'datetime', true, 150),
    UpdatedAt: col_(4, 'datetime', true, 150),
    Status: col_(5, 'enum', true, 120, 'queued, processing, processed, error.'),
    BookingSource: col_(6, 'string', true, 130),
    ExternalBookingId: col_(7, 'string', false, 180),
    Action: col_(8, 'string', true, 130),
    PayloadHash: col_(9, 'string', true, 180),
    PayloadJson: col_(10, 'json', true, 300),
    Error: col_(11, 'string', false, 280),
    ResultJson: col_(12, 'json', false, 260),
    ProcessedAt: col_(13, 'datetime', false, 150),
  }),

  DataFlowRef: Object.freeze({
    TabName: col_(1, 'string', true, 210),
    ColumnName: col_(2, 'string', true, 220),
    ColumnIndex: col_(3, 'integer', true, 100),
    Type: col_(4, 'string', true, 120),
    Required: col_(5, 'boolean', true, 100),
    Width: col_(6, 'integer', true, 90),
    OwnerRepo: col_(7, 'string', true, 220),
    Source: col_(8, 'string', false, 240),
    Invalidates: col_(9, 'string', false, 260),
    Notes: col_(10, 'string', false, 300),
  }),

  SchemaVersion: Object.freeze({
    CurrentVersion: col_(1, 'string', true, 140),
    LastSetupRunAt: col_(2, 'datetime', true, 160),
    LastSetupRunBy: col_(3, 'string', false, 220),
    SetupRevision: col_(4, 'string', false, 180),
    LastMigration: col_(5, 'string', false, 180),
    MigrationHistoryJson: col_(6, 'json', false, 300),
    VerificationStatus: col_(7, 'string', true, 160),
    Notes: col_(8, 'string', false, 300),
  }),

  OpsLog: Object.freeze({
    OpsLogID: col_(1, 'string', true, 170),
    Timestamp: col_(2, 'datetime', true, 160),
    ActorEmail: col_(3, 'string', false, 220),
    FunctionName: col_(4, 'string', true, 200),
    Tier: col_(5, 'enum', false, 100),
    Result: col_(6, 'string', true, 120),
    Message: col_(7, 'string', false, 300),
    LockWaitMs: col_(8, 'integer', false, 110),
    LockHoldMs: col_(9, 'integer', false, 110),
    Target: col_(10, 'string', false, 180),
    MetadataJson: col_(11, 'json', false, 260),
  }),
});

function schemaHeadersForTabKey_(tabKey) {
  var columns = SCHEMA_COLUMNS_BY_TAB_KEY[tabKey];
  return Object.keys(columns).sort(function(a, b) {
    return columns[a].col - columns[b].col;
  });
}

function schemaRowsForDataFlowRef_() {
  var rows = [];
  TAB_ORDER.forEach(function(tabKey) {
    var tabName = TAB_NAMES[tabKey];
    var ownerRepo = TAB_OWNER_REPOS[tabKey];
    var columns = SCHEMA_COLUMNS_BY_TAB_KEY[tabKey];
    schemaHeadersForTabKey_(tabKey).forEach(function(header) {
      var meta = columns[header];
      rows.push([
        tabName,
        header,
        meta.col,
        meta.type,
        meta.required,
        meta.width,
        ownerRepo,
        'canonical',
        cacheInvalidationForTabKey_(tabKey),
        meta.notes,
      ]);
    });
  });
  return rows;
}

function cacheInvalidationForTabKey_(tabKey) {
  var invalidations = {
    AppointmentEvents: 'CalendarMonthSlice,AppointmentBriefSlice,CustomerRootDetailSlice',
    RootAppointments: 'CustomerCardSlice,CustomerRootDetailSlice,AdminHealthSlice',
    CustomerInfo: 'TaskListSlice,CustomerCardSlice,CustomerRootDetailSlice,AdminHealthSlice',
    ClientStatus: 'TaskListSlice,CustomerCardSlice,CustomerRootDetailSlice,AdminHealthSlice',
    ClientStatusHistory: 'CustomerRootDetailSlice',
    Order3D: 'TaskListSlice,CustomerRootDetailSlice,AdminHealthSlice',
    Order3DHistory: 'CustomerRootDetailSlice',
    WaxRequests: 'TaskListSlice,CustomerRootDetailSlice,AdminHealthSlice',
    DiamondViewing: 'TaskListSlice,CustomerRootDetailSlice,DiamondTrackingSlice',
    Stones: 'TaskListSlice,CustomerRootDetailSlice,DiamondInventorySlice,DiamondTrackingSlice,DiamondRootSlice,AdminHealthSlice',
    StonesSync: 'DiamondInventorySlice,DiamondTrackingSlice,AdminHealthSlice',
    TaskQueue: 'TaskListSlice,TaskDetailSlice,CustomerRootDetailSlice',
    TaskLog: 'TaskDetailSlice,CustomerRootDetailSlice',
    AppointmentArtifacts: 'AppointmentBriefSlice,CustomerRootDetailSlice',
    Users: 'FormOptionsSlice,TaskListSlice',
    RosterSchedule: 'FormOptionsSlice,TaskListSlice',
    ScheduleChanges: 'FormOptionsSlice,TaskListSlice',
    Config: 'FormOptionsSlice',
    Templates: 'FormOptionsSlice,TaskDetailSlice',
    DataCleanup: 'TaskListSlice,AdminHealthSlice',
    IntakeQueue: 'AdminHealthSlice',
    DataFlowRef: '',
    SchemaVersion: '',
    OpsLog: 'AdminHealthSlice',
  };
  return invalidations[tabKey] || '';
}
